# Move the directory to the second line
format = '$all$directory$character'

[aws]
symbol = " "
format = "[$symbol]($style)"

[buf]
symbol = " "
format = "[$symbol]($style)"

[c]
symbol = " "
format = "[$symbol]($style)"

[conda]
symbol = " "
format = "[$symbol]($style)"

[crystal]
symbol = " "
format = "[$symbol]($style)"

[dart]
symbol = " "
format = "[$symbol]($style)"

[directory]
truncation_length = 1
truncation_symbol = '…/'
read_only = " 󰌾"

[docker_context]
symbol = " "
format = "[$symbol]($style)"

[elixir]
symbol = " "
format = "[$symbol]($style)"

[elm]
symbol = " "
format = "[$symbol]($style)"

[fennel]
symbol = " "
format = "[$symbol]($style)"

[fossil_branch]
symbol = " "
format = "[$symbol]($style)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) | "

[git_metrics]
disabled = false

[git_status]
ahead = '⇡${count}'
diverged = '⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
format = '([\[$conflicted$deleted$renamed$modified$staged$untracked$ahead_behind\]]($style) )'

[gcloud]
disabled = true

[golang]
symbol = " "
format = "[$symbol]($style)"

[guix_shell]
symbol = " "
format = "[$symbol]($style)"

[haskell]
symbol = " "
format = "[$symbol]($style)"

[haxe]
symbol = " "
format = "[$symbol]($style)"

[hg_branch]
symbol = " "
format = "[$symbol]($style)"

[hostname]
ssh_symbol = " "
format = "[$symbol]($style)"

[java]
symbol = " "
format = "[$symbol]($style)"

[julia]
symbol = " "
format = "[$symbol]($style)"

[kotlin]
symbol = " "
format = "[$symbol]($style)"

[lua]
symbol = " "
format = "[$symbol]($style)"

[memory_usage]
symbol = "󰍛 "
format = "[$symbol]($style)"

[meson]
symbol = " 󰔷"
format = "[$symbol]($style)"

[nim]
symbol = " 󰆥"
format = "[$symbol]($style)"

[nix_shell]
symbol = " "
format = "[$symbol]($style)"

[nodejs]
symbol = " "
format = "[$symbol]($style)"

[ocaml]
symbol = " "
format = "[$symbol]($style)"

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = " 󰏗"
format = "[$symbol]($style)"

[perl]
symbol = " "
format = "[$symbol]($style)"

[php]
symbol = " "
format = "[$symbol]($style)"

[pijul_channel]
symbol = " "
format = "[$symbol]($style)"

[python]
symbol = " "
format = "[$symbol]($style)"

[rlang]
symbol = " 󰟔"
format = "[$symbol]($style)"

[ruby]
symbol = " "
format = "[$symbol]($style)"

[rust]
symbol = " "
format = "[$symbol]($style)"

[scala]
symbol = " "
format = "[$symbol]($style)"

[swift]
symbol = " "
format = "[$symbol]($style)"

[zig]
symbol = " "
format = "[$symbol]($style)"